# MySQL. Versions 5.5.8 and up are supported.
#
# Install the MySQL driver
#   gem install mysql2
#
# Ensure the MySQL gem is defined in your Gemfile
#   gem "mysql2"
#
# And be sure to use new-style password hashing:
#   https://dev.mysql.com/doc/refman/5.7/en/password-hashing.html
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: wyatt_elevator
  password: Qazwsx24199@@@
  host: localhost

development:
  <<: *default
  database: wyatt_elevator_development

test:
  <<: *default
  database: wyatt_elevator_test

production:
  <<: *default
  database: wyatt_elevator_production
  username: wyatt_elevator
  password: <%= ENV['WYATT_ELEVATOR_PASSWORD'] %>
  host: <%= ENV['WYATT_ELEVATOR_HOST'] %>

